# Generated by Django 6.0.6 on 2026-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='head',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='recipient',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
