# Generated by Django 6.0.6 on 2026-06-14 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletters.message', verbose_name='Сообщение рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(to='newsletters.recipient', verbose_name='Список получателей'),
        ),
        migrations.AddField(
            model_name='userrecipientlink',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.recipient', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='userrecipientlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='users',
            field=models.ManyToManyField(through='newsletters.UserRecipientLink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userrecipientlink',
            constraint=models.UniqueConstraint(fields=('user', 'recipient'), name='unique_user_recipient'),
        ),
    ]
