# Generated by Django 6.0.6 on 2026-06-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipientlink',
            old_name='user',
            new_name='owner',
        ),
    ]
