# Generated by Django 6.0.6 on 2026-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_recipient_options_rename_body_message_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendTry',
            new_name='Attempt',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
    ]
