# Generated by Django 6.0.6 on 2026-06-14 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_rename_user_userrecipientlink_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrecipientlink',
            name='unique_user_recipient',
        ),
        migrations.AddConstraint(
            model_name='userrecipientlink',
            constraint=models.UniqueConstraint(fields=('owner', 'recipient'), name='unique_owner_recipient'),
        ),
    ]
