# Generated by Django 6.0.6 on 2026-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_remove_userrecipientlink_unique_user_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена'), ('Заблокирована', 'Заблокирована')], default='Создана', max_length=20, verbose_name='Статус рассылки'),
        ),
    ]
